Hooks: Fix pre-safe-import-module hook for 'setuptools.extern.six.moves'.
This had several issues:

1. The eval'ed code failed with an import error. I added a fall back.

2. Due to the eval'ed code failing, the result was a string, not a
   dict, causing the hooks code to fail.

3. Since the hook doe not fail on this error, a long backtrace is
   output, making user to report
     AttributeError: 'str' object has no attribute 'items'
   This will be handled in the next commit.